# Generated by Django 4.2.5 on 2024-08-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='query',
            new_name='title',
        ),
    ]
